// Code generated by "stringer -type EventType"; DO NOT EDIT.

package sdl

import "strconv"

const _EventType_name = "FIRSTEVENTQUITAPP_TERMINATINGAPP_LOWMEMORYAPP_WILLENTERBACKGROUNDAPP_DIDENTERBACKGROUNDAPP_WILLENTERFOREGROUNDAPP_DIDENTERFOREGROUNDWINDOWEVENTSYSWMEVENTKEYDOWNKEYUPTEXTEDITINGTEXTINPUTKEYMAPCHANGEDMOUSEMOTIONMOUSEBUTTONDOWNMOUSEBUTTONUPMOUSEWHEELJOYAXISMOTIONJOYBALLMOTIONJOYHATMOTIONJOYBUTTONDOWNJOYBUTTONUPJOYDEVICEADDEDJOYDEVICEREMOVEDCONTROLLERAXISMOTIONCONTROLLERBUTTONDOWNCONTROLLERBUTTONUPCONTROLLERDEVICEADDEDCONTROLLERDEVICEREMOVEDCONTROLLERDEVICEREMAPPEDFINGERDOWNFINGERUPFINGERMOTIONDOLLARGESTUREDOLLARRECORDMULTIGESTURECLIPBOARDUPDATEDROPFILEDROPTEXTDROPBEGINDROPCOMPLETEAUDIODEVICEADDEDAUDIODEVICEREMOVEDRENDER_TARGETS_RESETRENDER_DEVICE_RESETUSEREVENTLASTEVENT"

var _EventType_map = map[EventType]string{
	0:     _EventType_name[0:10],
	256:   _EventType_name[10:14],
	257:   _EventType_name[14:29],
	258:   _EventType_name[29:42],
	259:   _EventType_name[42:65],
	260:   _EventType_name[65:87],
	261:   _EventType_name[87:110],
	262:   _EventType_name[110:132],
	512:   _EventType_name[132:143],
	513:   _EventType_name[143:153],
	768:   _EventType_name[153:160],
	769:   _EventType_name[160:165],
	770:   _EventType_name[165:176],
	771:   _EventType_name[176:185],
	772:   _EventType_name[185:198],
	1024:  _EventType_name[198:209],
	1025:  _EventType_name[209:224],
	1026:  _EventType_name[224:237],
	1027:  _EventType_name[237:247],
	1536:  _EventType_name[247:260],
	1537:  _EventType_name[260:273],
	1538:  _EventType_name[273:285],
	1539:  _EventType_name[285:298],
	1540:  _EventType_name[298:309],
	1541:  _EventType_name[309:323],
	1542:  _EventType_name[323:339],
	1616:  _EventType_name[339:359],
	1617:  _EventType_name[359:379],
	1618:  _EventType_name[379:397],
	1619:  _EventType_name[397:418],
	1620:  _EventType_name[418:441],
	1621:  _EventType_name[441:465],
	1792:  _EventType_name[465:475],
	1793:  _EventType_name[475:483],
	1794:  _EventType_name[483:495],
	2048:  _EventType_name[495:508],
	2049:  _EventType_name[508:520],
	2050:  _EventType_name[520:532],
	2304:  _EventType_name[532:547],
	4096:  _EventType_name[547:555],
	4097:  _EventType_name[555:563],
	4098:  _EventType_name[563:572],
	4099:  _EventType_name[572:584],
	4352:  _EventType_name[584:600],
	4353:  _EventType_name[600:618],
	8192:  _EventType_name[618:638],
	8193:  _EventType_name[638:657],
	32768: _EventType_name[657:666],
	65535: _EventType_name[666:675],
}

func (i EventType) String() string {
	if str, ok := _EventType_map[i]; ok {
		return str
	}
	return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
}
